logging:
  level:
    root: INFO
application:
  python.path: python3 /root/python/
spring:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  datasource:
    url: jdbc:mysql://114.67.84.99:32306/stock?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800

dream:
  weixin:
    wx-configs:
      - appId: wx7834dc191378a252
        appSecret: d122217936541f396454677c68579b03
        token: 5f6e779a4d1043dba588afee04985286
        encodingAesKey: ZynfLkPjWQrPpnhJiy930XEXhr1N9iwI0nnWR3WBjSc